//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputLayoutCodeGenerator
//     version 1.7.0
//     from "HID::3Dconnexion SpaceNavigator MultiAxisController" layout
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

// Suppress warnings from local variables for control references
// that we don't end up using.
#pragma warning disable CS0219

namespace UnityEngine.InputSystem.HID
{
    public partial class FastHID : UnityEngine.InputSystem.HID.HID
    {
        public const string metadata = "AxisDeadzone;Stick;Vector2;Button;Axis;HID::3Dconnexion SpaceNavigator MultiAxisController;HID";
        public FastHID()
        {
            var builder = this.Setup(13, 6, 0)
                .WithName("3Dconnexion SpaceNavigator MultiAxisController")
                .WithDisplayName("SpaceNavigator")
                .WithChildren(0, 7)
                .WithLayout(new InternedString("HID::3Dconnexion SpaceNavigator MultiAxisController"))
                .WithStateBlock(new InputStateBlock { format = new FourCC(1212761120), sizeInBits = 56 });

            var kStickLayout = new InternedString("Stick");
            var kButtonLayout = new InternedString("Button");
            var kAxisLayout = new InternedString("Axis");

            // /3Dconnexion SpaceNavigator MultiAxisController/stick
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick(kStickLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/trigger
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger(kButtonLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/button2
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2 = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2(kButtonLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/z
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerz = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerz(kAxisLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/rz
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz(kAxisLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/ry
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerry = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerry(kAxisLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/rx
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerrx = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerrx(kAxisLayout, this);

            // /3Dconnexion SpaceNavigator MultiAxisController/stick/up
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup(kButtonLayout, ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);

            // /3Dconnexion SpaceNavigator MultiAxisController/stick/x
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx(kAxisLayout, ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);

            // /3Dconnexion SpaceNavigator MultiAxisController/stick/y
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky(kAxisLayout, ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);

            // /3Dconnexion SpaceNavigator MultiAxisController/stick/down
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown(kButtonLayout, ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);

            // /3Dconnexion SpaceNavigator MultiAxisController/stick/left
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft(kButtonLayout, ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);

            // /3Dconnexion SpaceNavigator MultiAxisController/stick/right
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright = Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright(kButtonLayout, ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);

            // Usages.
            builder.WithControlUsage(0, new InternedString("Primary2DMotion"), ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick);
            builder.WithControlUsage(1, new InternedString("PrimaryTrigger"), ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger);
            builder.WithControlUsage(2, new InternedString("PrimaryAction"), ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger);
            builder.WithControlUsage(3, new InternedString("SecondaryTrigger"), ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2);
            builder.WithControlUsage(4, new InternedString("SecondaryAction"), ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2);
            builder.WithControlUsage(5, new InternedString("Twist"), ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz);

            // Control getters/arrays.
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.up = ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup;
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.down = ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown;
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.left = ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft;
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.right = ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright;
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.x = ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx;
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.y = ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky;

            // State offset to control index map.
            builder.WithStateOffsetToControlIndexMap(new uint[]
            {
                4195329u, 4210694u, 4210696u, 4210699u, 4210700u, 4719618u, 12599301u, 12599303u, 12599305u, 12599306u
                , 20987907u, 20987908u
            });

            builder.WithControlTree(new byte[]
            {
                // Control tree nodes as bytes
                55, 0, 1, 0, 0, 0, 0, 24, 0, 5, 0, 0, 0, 1, 55, 0, 3, 0, 1, 0, 1, 40, 0, 255, 255, 2, 0, 4, 55, 0
                , 11, 0, 0, 0, 0, 10, 0, 7, 0, 6, 0, 4, 24, 0, 255, 255, 10, 0, 4, 8, 0, 255, 255, 0, 0, 0, 10, 0, 9, 0
                , 0, 0, 0, 9, 0, 255, 255, 14, 0, 1, 10, 0, 255, 255, 15, 0, 1, 48, 0, 255, 255, 16, 0, 2, 55, 0, 255, 255, 18, 0
                , 2
            }, new ushort[]
                {
                    // Control tree node indicies

                    0, 0, 7, 9, 10, 5, 8, 11, 12, 6, 8, 11, 12, 6, 1, 2, 3, 4, 3, 4
                });

            builder.Finish();
        }

        private UnityEngine.InputSystem.Controls.StickControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick(InternedString kStickLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick = new UnityEngine.InputSystem.Controls.StickControl();
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick.Setup()
                .At(this, 0)
                .WithParent(parent)
                .WithChildren(7, 6)
                .WithName("stick")
                .WithDisplayName("Stick")
                .WithLayout(kStickLayout)
                .WithUsages(0, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447379762),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerstick;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger.Setup()
                .At(this, 1)
                .WithParent(parent)
                .WithName("trigger")
                .WithDisplayName("Trigger")
                .WithLayout(kButtonLayout)
                .WithUsages(1, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllertrigger;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2.Setup()
                .At(this, 2)
                .WithParent(parent)
                .WithName("button2")
                .WithDisplayName("Button 2")
                .WithLayout(kButtonLayout)
                .WithUsages(3, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 1,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerbutton2;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerz(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerz = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerz.Setup()
                .At(this, 3)
                .WithParent(parent)
                .WithName("z")
                .WithDisplayName("Z")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 5,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerz;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz.Setup()
                .At(this, 4)
                .WithParent(parent)
                .WithName("rz")
                .WithDisplayName("Rz")
                .WithLayout(kAxisLayout)
                .WithUsages(5, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 5,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerrz;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerry(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerry = new UnityEngine.InputSystem.Controls.AxisControl { invert = true, normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerry.Setup()
                .At(this, 5)
                .WithParent(parent)
                .WithName("ry")
                .WithDisplayName("Ry")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerry;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerrx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerrx = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerrx.Setup()
                .At(this, 6)
                .WithParent(parent)
                .WithName("rx")
                .WithDisplayName("Rx")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerrx;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMin = -1f, invert = true, normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup.Setup()
                .At(this, 7)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("Stick Up")
                .WithShortDisplayName("Stick Up")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickup;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx.Setup()
                .At(this, 8)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Stick X")
                .WithShortDisplayName("Stick X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky = new UnityEngine.InputSystem.Controls.AxisControl { invert = true, normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky.Setup()
                .At(this, 9)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Stick Y")
                .WithShortDisplayName("Stick Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllersticky;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMax = 1f, normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown.Setup()
                .At(this, 10)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("Stick Down")
                .WithShortDisplayName("Stick Down")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickdown;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMin = -1f, invert = true, normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft.Setup()
                .At(this, 11)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("Stick Left")
                .WithShortDisplayName("Stick Left")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickleft;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMax = 1f, normalize = true, normalizeMin = -0.01524377f, normalizeMax = 0.01527429f, normalizeZero = 1.525879E-05f };
            ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright.Setup()
                .At(this, 12)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("Stick Right")
                .WithShortDisplayName("Stick Right")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceNavigatorMultiAxisControllerstickright;
        }
    }
}
