//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputLayoutCodeGenerator
//     version 1.7.0
//     from "HID::3Dconnexion SpaceM MultiAxisController" layout
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

// Suppress warnings from local variables for control references
// that we don't end up using.
#pragma warning disable CS0219

namespace UnityEngine.InputSystem.HID
{
    public partial class FastHidSpaceMousePro : UnityEngine.InputSystem.HID.HID
    {
        public const string metadata = "AxisDeadzone;Stick;Vector2;Button;Axis;HID::3Dconnexion SpaceM MultiAxisController;HID";
        public FastHidSpaceMousePro()
        {
            var builder = this.Setup(26, 6, 0)
                .WithName("3Dconnexion SpaceM MultiAxisController")
                .WithDisplayName("SpaceM")
                .WithChildren(0, 20)
                .WithLayout(new InternedString("HID::3Dconnexion SpaceM MultiAxisController"))
                .WithStateBlock(new InputStateBlock { format = new FourCC(1212761120), sizeInBits = 56 });

            var kStickLayout = new InternedString("Stick");
            var kButtonLayout = new InternedString("Button");
            var kAxisLayout = new InternedString("Axis");

            // /3Dconnexion SpaceM MultiAxisController/stick
            var ctrl3DconnexionSpaceMMultiAxisControllerstick = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstick(kStickLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/trigger
            var ctrl3DconnexionSpaceMMultiAxisControllertrigger = Initialize_ctrl3DconnexionSpaceMMultiAxisControllertrigger(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button2
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton2 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton2(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button3
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton3 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton3(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button5
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton5 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton5(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button6
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton6 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton6(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button9
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton9 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton9(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button13
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton13 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton13(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button14
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton14 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton14(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button15
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton15 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton15(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button16
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton16 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton16(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button23
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton23 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton23(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button24
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton24 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton24(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button25
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton25 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton25(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button26
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton26 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton26(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/button27
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton27 = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton27(kButtonLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/z
            var ctrl3DconnexionSpaceMMultiAxisControllerz = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerz(kAxisLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/rz
            var ctrl3DconnexionSpaceMMultiAxisControllerrz = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerrz(kAxisLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/ry
            var ctrl3DconnexionSpaceMMultiAxisControllerry = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerry(kAxisLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/rx
            var ctrl3DconnexionSpaceMMultiAxisControllerrx = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerrx(kAxisLayout, this);

            // /3Dconnexion SpaceM MultiAxisController/stick/up
            var ctrl3DconnexionSpaceMMultiAxisControllerstickup = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickup(kButtonLayout, ctrl3DconnexionSpaceMMultiAxisControllerstick);

            // /3Dconnexion SpaceM MultiAxisController/stick/x
            var ctrl3DconnexionSpaceMMultiAxisControllerstickx = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickx(kAxisLayout, ctrl3DconnexionSpaceMMultiAxisControllerstick);

            // /3Dconnexion SpaceM MultiAxisController/stick/y
            var ctrl3DconnexionSpaceMMultiAxisControllersticky = Initialize_ctrl3DconnexionSpaceMMultiAxisControllersticky(kAxisLayout, ctrl3DconnexionSpaceMMultiAxisControllerstick);

            // /3Dconnexion SpaceM MultiAxisController/stick/down
            var ctrl3DconnexionSpaceMMultiAxisControllerstickdown = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickdown(kButtonLayout, ctrl3DconnexionSpaceMMultiAxisControllerstick);

            // /3Dconnexion SpaceM MultiAxisController/stick/left
            var ctrl3DconnexionSpaceMMultiAxisControllerstickleft = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickleft(kButtonLayout, ctrl3DconnexionSpaceMMultiAxisControllerstick);

            // /3Dconnexion SpaceM MultiAxisController/stick/right
            var ctrl3DconnexionSpaceMMultiAxisControllerstickright = Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickright(kButtonLayout, ctrl3DconnexionSpaceMMultiAxisControllerstick);

            // Usages.
            builder.WithControlUsage(0, new InternedString("Primary2DMotion"), ctrl3DconnexionSpaceMMultiAxisControllerstick);
            builder.WithControlUsage(1, new InternedString("PrimaryTrigger"), ctrl3DconnexionSpaceMMultiAxisControllertrigger);
            builder.WithControlUsage(2, new InternedString("PrimaryAction"), ctrl3DconnexionSpaceMMultiAxisControllertrigger);
            builder.WithControlUsage(3, new InternedString("SecondaryTrigger"), ctrl3DconnexionSpaceMMultiAxisControllerbutton2);
            builder.WithControlUsage(4, new InternedString("SecondaryAction"), ctrl3DconnexionSpaceMMultiAxisControllerbutton2);
            builder.WithControlUsage(5, new InternedString("Twist"), ctrl3DconnexionSpaceMMultiAxisControllerrz);

            // Control getters/arrays.
            ctrl3DconnexionSpaceMMultiAxisControllerstick.up = ctrl3DconnexionSpaceMMultiAxisControllerstickup;
            ctrl3DconnexionSpaceMMultiAxisControllerstick.down = ctrl3DconnexionSpaceMMultiAxisControllerstickdown;
            ctrl3DconnexionSpaceMMultiAxisControllerstick.left = ctrl3DconnexionSpaceMMultiAxisControllerstickleft;
            ctrl3DconnexionSpaceMMultiAxisControllerstick.right = ctrl3DconnexionSpaceMMultiAxisControllerstickright;
            ctrl3DconnexionSpaceMMultiAxisControllerstick.x = ctrl3DconnexionSpaceMMultiAxisControllerstickx;
            ctrl3DconnexionSpaceMMultiAxisControllerstick.y = ctrl3DconnexionSpaceMMultiAxisControllersticky;

            // State offset to control index map.
            builder.WithStateOffsetToControlIndexMap(new uint[]
            {
                4195329u, 4210707u, 4210709u, 4210712u, 4210713u, 4719618u, 5243907u, 6292484u, 6816773u, 8389638u
                , 10486791u, 11011080u, 11535369u, 12059658u, 12599314u, 12599316u, 12599318u, 12599319u, 15729675u, 16253964u
                , 16778253u, 17302542u, 17826831u, 20987920u, 20987921u
            });

            builder.WithControlTree(new byte[]
            {
                // Control tree nodes as bytes
                55, 0, 1, 0, 0, 0, 0, 31, 0, 3, 0, 0, 0, 5, 55, 0, 39, 0, 5, 0, 5, 16, 0, 5, 0, 10, 0, 4, 31, 0
                , 19, 0, 14, 0, 4, 8, 0, 255, 255, 0, 0, 0, 16, 0, 7, 0, 0, 0, 0, 11, 0, 9, 0, 0, 0, 0, 16, 0, 13, 0
                , 0, 0, 0, 10, 0, 11, 0, 0, 0, 0, 11, 0, 255, 255, 20, 0, 1, 9, 0, 255, 255, 18, 0, 1, 10, 0, 255, 255, 19, 0
                , 1, 14, 0, 15, 0, 0, 0, 0, 16, 0, 255, 255, 0, 0, 0, 13, 0, 17, 0, 0, 0, 0, 14, 0, 255, 255, 22, 0, 1, 12
                , 0, 255, 255, 0, 0, 0, 13, 0, 255, 255, 21, 0, 1, 24, 0, 21, 0, 0, 0, 0, 31, 0, 35, 0, 0, 0, 0, 21, 0, 23
                , 0, 0, 0, 0, 24, 0, 31, 0, 0, 0, 0, 19, 0, 25, 0, 0, 0, 0, 21, 0, 29, 0, 0, 0, 0, 18, 0, 27, 0, 0
                , 0, 0, 19, 0, 255, 255, 0, 0, 0, 17, 0, 255, 255, 23, 0, 1, 18, 0, 255, 255, 0, 0, 0, 20, 0, 255, 255, 0, 0, 0
                , 21, 0, 255, 255, 24, 0, 1, 23, 0, 33, 0, 0, 0, 0, 24, 0, 255, 255, 27, 0, 1, 22, 0, 255, 255, 25, 0, 1, 23, 0
                , 255, 255, 26, 0, 1, 28, 0, 255, 255, 0, 0, 0, 31, 0, 37, 0, 0, 0, 0, 30, 0, 255, 255, 0, 0, 0, 31, 0, 255, 255
                , 28, 0, 1, 40, 0, 41, 0, 0, 0, 0, 55, 0, 49, 0, 0, 0, 0, 35, 0, 43, 0, 0, 0, 0, 40, 0, 255, 255, 0, 0
                , 0, 33, 0, 45, 0, 0, 0, 0, 35, 0, 47, 0, 0, 0, 0, 32, 0, 255, 255, 29, 0, 1, 33, 0, 255, 255, 30, 0, 1, 34
                , 0, 255, 255, 31, 0, 1, 35, 0, 255, 255, 32, 0, 1, 48, 0, 255, 255, 33, 0, 2, 55, 0, 255, 255, 35, 0, 2
            }, new ushort[]
                {
                    // Control tree node indicies

                    0, 20, 22, 23, 18, 0, 20, 22, 23, 18, 21, 24, 25, 19, 21, 24, 25, 19, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
                    , 13, 14, 15, 16, 17, 16, 17
                });

            builder.Finish();
        }

        private UnityEngine.InputSystem.Controls.StickControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstick(InternedString kStickLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerstick = new UnityEngine.InputSystem.Controls.StickControl();
            ctrl3DconnexionSpaceMMultiAxisControllerstick.Setup()
                .At(this, 0)
                .WithParent(parent)
                .WithChildren(20, 6)
                .WithName("stick")
                .WithDisplayName("Stick")
                .WithLayout(kStickLayout)
                .WithUsages(0, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447379762),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerstick;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllertrigger(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllertrigger = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllertrigger.Setup()
                .At(this, 1)
                .WithParent(parent)
                .WithName("trigger")
                .WithDisplayName("Trigger")
                .WithLayout(kButtonLayout)
                .WithUsages(1, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllertrigger;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton2(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton2 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton2.Setup()
                .At(this, 2)
                .WithParent(parent)
                .WithName("button2")
                .WithDisplayName("Button 2")
                .WithLayout(kButtonLayout)
                .WithUsages(3, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 1,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton2;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton3(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton3 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton3.Setup()
                .At(this, 3)
                .WithParent(parent)
                .WithName("button3")
                .WithDisplayName("Button 3")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 2,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton3;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton5(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton5 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton5.Setup()
                .At(this, 4)
                .WithParent(parent)
                .WithName("button5")
                .WithDisplayName("Button 5")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 4,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton5;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton6(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton6 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton6.Setup()
                .At(this, 5)
                .WithParent(parent)
                .WithName("button6")
                .WithDisplayName("Button 6")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 1,
                    bitOffset = 5,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton6;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton9(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton9 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton9.Setup()
                .At(this, 6)
                .WithParent(parent)
                .WithName("button9")
                .WithDisplayName("Button 9")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 2,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton9;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton13(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton13 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton13.Setup()
                .At(this, 7)
                .WithParent(parent)
                .WithName("button13")
                .WithDisplayName("Button 13")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 2,
                    bitOffset = 4,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton13;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton14(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton14 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton14.Setup()
                .At(this, 8)
                .WithParent(parent)
                .WithName("button14")
                .WithDisplayName("Button 14")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 2,
                    bitOffset = 5,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton14;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton15(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton15 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton15.Setup()
                .At(this, 9)
                .WithParent(parent)
                .WithName("button15")
                .WithDisplayName("Button 15")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 2,
                    bitOffset = 6,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton15;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton16(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton16 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton16.Setup()
                .At(this, 10)
                .WithParent(parent)
                .WithName("button16")
                .WithDisplayName("Button 16")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 2,
                    bitOffset = 7,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton16;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton23(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton23 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton23.Setup()
                .At(this, 11)
                .WithParent(parent)
                .WithName("button23")
                .WithDisplayName("Button 23")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 3,
                    bitOffset = 6,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton23;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton24(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton24 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton24.Setup()
                .At(this, 12)
                .WithParent(parent)
                .WithName("button24")
                .WithDisplayName("Button 24")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 3,
                    bitOffset = 7,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton24;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton25(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton25 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton25.Setup()
                .At(this, 13)
                .WithParent(parent)
                .WithName("button25")
                .WithDisplayName("Button 25")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 4,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton25;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton26(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton26 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton26.Setup()
                .At(this, 14)
                .WithParent(parent)
                .WithName("button26")
                .WithDisplayName("Button 26")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 4,
                    bitOffset = 1,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton26;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerbutton27(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerbutton27 = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrl3DconnexionSpaceMMultiAxisControllerbutton27.Setup()
                .At(this, 15)
                .WithParent(parent)
                .WithName("button27")
                .WithDisplayName("Button 27")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 4,
                    bitOffset = 2,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerbutton27;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerz(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerz = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerz.Setup()
                .At(this, 16)
                .WithParent(parent)
                .WithName("z")
                .WithDisplayName("Z")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 5,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerz;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerrz(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerrz = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerrz.Setup()
                .At(this, 17)
                .WithParent(parent)
                .WithName("rz")
                .WithDisplayName("Rz")
                .WithLayout(kAxisLayout)
                .WithUsages(5, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 5,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerrz;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerry(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerry = new UnityEngine.InputSystem.Controls.AxisControl { invert = true, normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerry.Setup()
                .At(this, 18)
                .WithParent(parent)
                .WithName("ry")
                .WithDisplayName("Ry")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerry;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerrx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerrx = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerrx.Setup()
                .At(this, 19)
                .WithParent(parent)
                .WithName("rx")
                .WithDisplayName("Rx")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(0)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerrx;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickup(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerstickup = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMin = -1f, invert = true, normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerstickup.Setup()
                .At(this, 20)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("Stick Up")
                .WithShortDisplayName("Stick Up")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerstickup;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerstickx = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerstickx.Setup()
                .At(this, 21)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Stick X")
                .WithShortDisplayName("Stick X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerstickx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllersticky(InternedString kAxisLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllersticky = new UnityEngine.InputSystem.Controls.AxisControl { invert = true, normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllersticky.Setup()
                .At(this, 22)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Stick Y")
                .WithShortDisplayName("Stick Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllersticky;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickdown(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerstickdown = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMax = 1f, normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerstickdown.Setup()
                .At(this, 23)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("Stick Down")
                .WithShortDisplayName("Stick Down")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerstickdown;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickleft(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerstickleft = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMin = -1f, invert = true, normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerstickleft.Setup()
                .At(this, 24)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("Stick Left")
                .WithShortDisplayName("Stick Left")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerstickleft;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrl3DconnexionSpaceMMultiAxisControllerstickright(InternedString kButtonLayout, InputControl parent)
        {
            var ctrl3DconnexionSpaceMMultiAxisControllerstickright = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.AfterNormalize, clampMax = 1f, normalize = true, normalizeMin = -0.01066607f, normalizeMax = 0.01069653f, normalizeZero = 1.522899E-05f };
            ctrl3DconnexionSpaceMMultiAxisControllerstickright.Setup()
                .At(this, 25)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("Stick Right")
                .WithShortDisplayName("Stick Right")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1396853076),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithDefaultState(-32767)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrl3DconnexionSpaceMMultiAxisControllerstickright;
        }
    }
}
